version: "3.8"
services:
  spring-app:
    build: .
    depends_on:
      - mysql-db
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    command: [ "sh", "-c", "until nc -z mysql-db 3306; do echo waiting for mysql-db; sleep 2; done; java -jar quanlydoantotnghiep.jar" ]
    networks:
      - spring-net

  mysql-db:
    image: mysql:8.4.4
    restart: always
    environment:
      MYSQL_DATABASE: db_quanlydoantotnghiep
      MYSQL_ROOT_PASSWORD: dat03122003
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql # save datas from db to volumes
    networks:
      - spring-net

networks:
  spring-net:

volumes:
  mysql-data: