server:
  port: 8989

spring:
  application:
    name: QuanLyDoAnTotNghiep
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/doantotnghiep
    username: root
    password: dat03122003
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: dat03122003@gmail.com
    password: mbexygkxtooqqhda
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

##config jwt
#app:
#  jwt-secret: c0599befa5c9127ae1339c723e60a6bb297e25688c4fc23794a9eba968fd63d4 #jwt secret key : dangquocdat (sha256 ecrypt)
#  jwt-expiration-milliseconds: 1300000 # 5 minutes
