server:
  port: ${PORT:8080}

spring:
  application:
    name: QuanLyDoAnTotNghiep_docker
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://gateway01.ap-southeast-1.prod.aws.tidbcloud.com:4000/test
    username: 497MCcedzi5DjR8.root
    password: FuilwpINS3t7aiLi
  #    url: jdbc:mysql://metro.proxy.rlwy.net:53397/db_doantotnghiep_production
#    username: root
#    password: OWAsVJUWoTayepzqfrxWwqOIHaUCTBix

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    database-platform: org.hibernate.dialect.TiDBDialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: dat03122003@gmail.com
    password: mbexygkxtooqqhda
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

#config jwt
app:
  jwt-secret: c0599befa5c9127ae1339c723e60a6bb297e25688c4fc23794a9eba968fd63d4 #jwt secret key : dangquocdat (sha256 ecrypt)
  jwt-expiration-milliseconds: 1300000 # 5 minutes
